apis/urls.py
from django.conf.urls import include, url 
from apis.views import ApisView 
 
 
urlpatterns = [  
    url(r'^apis/$', ApisView.as_view(), name='apis'),      
]

sitecontent/urls.py
from django.conf.urls import   url 
from sitecontent.views import BlockContentView, BlockItemContentView
from sitecontent import views
 
urlpatterns = [  
    url(r'^blockcontents/$', BlockContentView.as_view(), name='blockcontents'),       
    url(r'^blockitemcontents/$', BlockItemContentView.as_view(), name='blockitemcontents'),       
]

sitecontent/models.py
# -*- coding:utf-8 -*-
from django.db import models
from appuser.models import AdaptorUser as User

from sitecontent.manager import AdaptorSiteContentManager

class BaseBlock(models.Model):
    """
    模块,如：主轮播图、热销产品模块
    """
    STATUS_SHOW = 1
    STATUS_HIDE = 0
    user = models.ForeignKey(User)
    # 模块展示时显示的图片
    pic = models.CharField(max_length = 1024, null= True)
    # 模块地址
    url = models.CharField(max_length = 1024, null = True) 
    # 模块名称
    title = models.CharField(max_length = 512) 
    # 模块状态：显示或隐藏
    status = models.SmallIntegerField(default = STATUS_SHOW) 
    # 标记被显示在什么位置：如主轮播图中
    mark = models.CharField(max_length = 128) 
    class Meta:
        abstract = True
        
class AdaptorBaseBlock(BaseBlock):
    objects = AdaptorSiteContentManager()
    

class BaseBlockItem(models.Model):
    """
    模块中的具体展示元素信息， 如主轮播图中的产品、热销产品模块中的产品
    """
    STATUS_SHOW = 1
    STATUS_HIDE = 0 
    block = models.ForeignKey(AdaptorBaseBlock) 
    # item展示时显示的图片
    pic = models.CharField(max_length = 1024 )
    # item详情地址
    url = models.CharField(max_length = 1024 ) 
    # item名称
    title = models.CharField(max_length = 512) 
    # item状态：显示或隐藏
    status = models.SmallIntegerField(default = STATUS_SHOW) 
    class Meta:
        abstract = True
     
class AdaptorBaseBlockItem(BaseBlockItem): 
    pass
    

sitecontent/views.py
#! -*- coding:utf-8 -*-
import pdb
import json
import random
import string
import os
from datetime import datetime

from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.http import Http404, QueryDict
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from django.conf import settings
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status 
from django.utils.translation import ugettext as _

from sitecontent import models
from sitecontent.comm import handle_uploaded_file

from mobile.detectmobilebrowsermiddleware import DetectMobileBrowser
dmb     = DetectMobileBrowser()

class BlockContentView(View):

    @method_decorator(login_required)
    def get(self, request):
        isMble  = dmb.process_request(request)
        content = {} 
        blocks = models.AdaptorBaseBlock.objects.all()
     
        content['blocks'] = blocks
        content['mediaroot'] = settings.MEDIA_URL
        if 'new' in request.GET:
            if isMble:
                return render(request, 'sitecontent/m_blocknew.html', content)
            else:
                return render(request, 'sitecontent/blocknew.html', content)

        if 'test' in request.GET:
            if isMble:
                return render(request, 'sitecontent/test.html', content)
            else:
                return render(request, 'sitecontent/test.html', content)
        if 'detail' in request.GET:
            if isMble:
                return render(request, 'sitecontent/m_detail.html', content)
            else:
                return render(request, 'sitecontent/m_detail.html', content)
        else:
            if isMble:
                return render(request, 'sitecontent/m_lists.html', content)
            else:
                return render(request, 'sitecontent/m_lists.html', content)

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def post(self,request ): 
        if 'method' in request.POST:
            method = request.POST['method'].lower()
            if method == 'put':# 修改
                self.put(request)
                return   self.get(request)
            elif method == 'create': # 创建
                return self.create(request) 
            elif method == 'delete': # 删除
                return self.delete(request) 
        else:
            self.create(request)
            return self.get(request)

    def create(self, request):
        """创建""" 
        # 创建时：title字段是必须的,\url\pic\mark\status是可选字段
        user = request.user
        result = {} 
        
        if 'title' in request.POST : 
            title = request.POST['title'].strip() 

            # 创建Block 
            block = models.AdaptorBaseBlock.objects.create(user=user, title=title )
            
            if 'url' in request.POST  :
                url = request.POST['url'].strip()
                block.url = url
  
            if 'pic' in request.FILES:
                pic = request.FILES['pic'] 
                pic_url = handle_uploaded_file(pic, user.id)
                block.pic = pic_url
            
            if 'mark' in request.POST:
                mark = request.POST['mark'].strip() 
                if mark:
                    block.mark = mark
            
            if 'status' in request.POST:
                status = request.POST['status'].strip() 
                if int(status):
                    block.status = int(status)
    
            block.save()
            result['id'] = block.id
            result['status'] ='ok'
            result['msg'] = _('Saved completely!') 
        else:
            result['status'] ='error'
            result['msg'] ='Need title  in POST'
        return self.httpjson(result)
    
    def put(self, request):
        """修改""" 
        # 修改时：blockid字段是必须的,title\url\pic\mark\status是可选字段
        user = request.user
        result = {}
        if 'blockid' in request.POST : 
            blockid = request.POST['blockid'].strip() 

            # 创建Block 
            block = models.AdaptorBaseBlock.objects.get(pk = blockid)
            
            if  'title' in request.POST  :
                title = request.POST['title'].strip()
                block.title = title
            
            if 'pic' in request.FILES:
                pic = request.FILES['pic'] 
                pic_url = handle_uploaded_file(pic, user.id)
                block.pic = pic_url

            if  'url' in request.POST  :
                url = request.POST['url'].strip()
                block.url = url
            
            if 'mark' in request.POST:
                mark = request.POST['mark'].strip() 
                if mark:
                    block.mark = mark
            
            if 'status' in request.POST:
                status = request.POST['status'].strip()   
                block.status = int(status)
            
            block.save()
            result['id'] = block.id
            result['status'] ='ok'
            result['msg'] = _('Saved completely!') 
        else:
            result['status'] ='error'
            result['msg'] ='Need title  in POST'
        return self.httpjson(result)

    def delete(self, request):
        user = request.user
        result = {}
        if 'id' in request.POST : 
            blockid = request.POST['id'].strip() 
            try:
                block = models.AdaptorBaseBlock.objects.get(pk = blockid)
                block.delete()
                result['status'] ='ok'
                result['msg'] = _('Done')
            except models.AdaptorBaseBlock.DoesNotExist:
                result['status'] ='error'
                result['msg'] = _('Not found')
        else:
            result['status'] ='error'
            result['msg'] = 'Need title  in POST'
        
        return self.httpjson(result)

    def httpjson(self, result):
        return HttpResponse(json.dumps(result), content_type="application/json")



class BlockItemContentView(View):
    @method_decorator(login_required)
    def get(self, request):
        isMble  = dmb.process_request(request)
        content = {}   
        content['mediaroot'] = settings.MEDIA_URL
        if 'blockid' in request.GET:
            blockid = request.GET['blockid'].strip()  
            try:
                block = models.AdaptorBaseBlock.objects.get(pk = blockid )
  
                content['block_instance'] = block
            except models.AdaptorBaseBlock.DoesNotExist:
                raise Http404
                
        if 'new' in request.GET:
            if isMble:
                return render(request, 'sitecontent/m_new.html', content)
            else:
                return render(request, 'sitecontent/new.html', content)
        
        if 'test' in request.GET:
            if isMble:
                return render(request, 'sitecontent/testitem.html', content)
            else:
                return render(request, 'sitecontent/testitem.html', content)

        if 'detail' in request.GET:
            if isMble:
                return render(request, 'sitecontent/m_detail.html', content)
            else:
                return render(request, 'sitecontent/m_detail.html', content)
       
        else:
            if isMble:
                return render(request, 'sitecontent/m_lists.html', content)
            else:
                return render(request, 'sitecontent/m_lists.html', content)

    @method_decorator(login_required)
    @method_decorator(csrf_exempt)
    def post(self,request ):
        if 'method' in request.POST:
            method = request.POST['method'].lower()
            if method == 'put':# 修改
                self.put(request)
                return   self.get(request)
            elif method == 'delete': # 删除
                return self.delete(request) 
            elif method == 'create': # 创建
                return self.create(request) 
        else:
            self.create(request)
            return self.get(request)

    def create(self, request):
        """创建""" 
        # 创建时：blockid,title字段是必须的,\url\pic\mark\status是可选字段
        user = request.user
        result = {} 
        
        if 'blockid' in request.POST and 'title' in request.POST : 
            title = request.POST['title'].strip() 
            blockid = request.POST['blockid'].strip() 
          

            try:
                block = models.AdaptorBaseBlock.objects.get(pk = blockid )
                item = models.AdaptorBaseBlockItem.objects.create(block = block, title = title )
                if 'url' in request.POST  :
                    url = request.POST['url'].strip()
                    item.url = url
    
                if 'pic' in request.FILES:
                    pic = request.FILES['pic'] 
                    pic_url = handle_uploaded_file(pic, user.id)
                    item.pic = pic_url
                
                if 'mark' in request.POST:
                    mark = request.POST['mark'].strip() 
                    if mark:
                        item.mark = mark
                
                if 'status' in request.POST:
                    status = request.POST['status'].strip() 
                    if status:
                        item.status = status
        
                item.save()
                result['id'] = item.id
                result['status'] ='ok'
                result['msg'] = _('Saved completely!') 
            except models.AdaptorBaseBlock.DoesNotExist:
                result['status'] ='error'
                result['msg'] = _('Not found')
        else:
            result['status'] ='error'
            result['msg'] ='Need title  in POST'
        return self.httpjson(result)
    
    def put(self, request):
        """修改""" 

sitecontent/templates/sitecontent/blocknew.html
{% extends 'base.html' %}
{% load i18n %}
{% block pagetitle%}{% trans 'Homepage Content Management' %}{% endblock%}
{% block css %}
<link href="/static/sitecontent/css/blocknew.css" rel="stylesheet">
 {% endblock %}
{% block content %}
<form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%} 
    <input type="hidden" name="method" value="detail_file" /> 
    {% if block_instance %}
    <input type="hidden" name="blockid" id="blockid" value="{{block_instance.id}}" /> 
    {% endif %}
</form>
<section class="container">

    <div class="row">

        <div class="form_title">首页模块控制</div>

        <form class="form_main form-horizontal" action="" method="post"  enctype="multipart/form-data">
            {%csrf_token%}   
            <div id="add_input">
            </div>
            <div class="form-group">
                <label for="title" class="col-sm-2 control-label">{% trans "title" %}</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="title" name="title" required="required" placeholder="{% trans "title" %}">
                </div>
            </div>

            <div class="form-group">
                <label for="url" class="col-sm-2 control-label">链接</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="url" name="url" title="url" placeholder="url">
                </div>
            </div>  

            <div class="form-group">
                <label for="status" class="col-sm-2 control-label">{% trans "status" %}</label>
                <div class="col-sm-10">
                        <select class="form-control" id="status" name="status" >
                                <option value ="0">草稿</option>
                                <option value ="1">发布</option>
                        </select>
                </div>
            </div>
            <div class="form-group">
                    <label for="mark" class="col-sm-2 control-label">标记</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="mark" name="mark" title="{% trans "mark" %}" placeholder="{% trans "mark" %}">
                    </div>
            </div>
            <div class="form-group">
            
                <div id="wrapper" class="col-sm-2">
                    <input class="hide" id="fileUpload" type="file" name="pic" />
                    <div class="img_wrap" id="image-holder">
                        <img class="thumb-image" src="/static/img/pic1.png" />
                    </div>
                </div>
            
                <div class="col-sm-10">
                    <label id="file" for="fileUpload" class="control-label btn btn-primary" title="上传图片">上传图片
                            <i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
                    </label>
                    <button type="submit" class="btn btn-primary" title="{% trans "submit" %}">{% trans "submit" %}</button>
                </div>

            </div>

        </form>
        <div class="table_wrap col-sm-12 col-md-12">
                <table class="table table-striped table-hover table-bordered">
                        <tr>
                            <th>ID</th>
                            <th>{% trans "title" %}</th>
                            <th>{% trans "picture" %}</th>
                            <th>链接</th>
                            <th>{% trans "status" %}</th>
                            <th>{% trans "mark" %}</th>
                            <th>操作</th>
                        </tr>
                    {% for blocki in blocks %}
                    <tr class="table_con"> 
                        <td class="b_id">{{blocki.id}}</td>
                        <td class="b_title"><a target="__blank" href="{% url 'sitecontent:blockitemcontents' %}?new=&blockid={{blocki.id}}">{{blocki.title}}</a></td>
                        <td class="b_picture"><a target="__blank" href="{{mediaroot}}{{blocki.pic}}">点击查看图片</a></td>
                        <td class="b_url"><a target="__blank" href="{{blocki.url}}">{{blocki.url}}</a></td>
                        
                        {% if blocki.status == 0 %}
                        <td class="b_status">草稿</td>
                        {% else %}
                        <td class="b_status">发布</td>
                        {% endif %}
                        <td class="b_mark">{{blocki.mark}}</td>
                        <td class="text-center">
                            <i class="fa fa-pencil-square-o edit" aria-hidden="true" title="编辑"></i>
                            <i class="fa fa-trash-o" aria-hidden="true" title='删除'></i>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
    </div>
</section>
{% endblock%}{% block js %}
<script type="text/javascript" src="/static/sitecontent/js/blocknew.js"></script>
{% endblock %}

sitecontent/templates/sitecontent/m_lists.html
{% extends 'base.html' %} {% block menu %} {% endblock %} {% block footer %}{% endblock %} {% block css %}
<link href="/static/sitecontent/css/sitecontent.css" rel="stylesheet"> {% endblock %} {% block content %}
<header>

</header>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2 sidebar">
            <div class="user_photo">
                <img class="img-circle" src="/static/img/list1.jpg">
            </div>
            <div>昵称&管理员</div>
            <ul>
                <li>设置</li>
                <li>设置</li>
                <li>设置</li>
                <li>设置</li>
            </ul>
        </div>
        <div class="col-sm-9 col-md-9 col-lg-9">

        </div>
    </div>
</div>

{% endblock %} {% block js %}<script type="text/javascript " src="/static/sitecontent/js/sitecontent.js"></script>
 {% endblock %}

sitecontent/templates/sitecontent/new.html
{% extends 'base.html' %} 
{% load i18n %}
{% block css %}
<link href="/static/sitecontent/css/blocknew.css" rel="stylesheet">
 {% endblock %}
 {% block content %}
 <form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%} 
    <input type="hidden" name="method" value="detail_file" /> 
    {% if block_instance %}
    <input type="hidden" name="blockid" id="blockid" value="{{block_instance.id}}" /> 
    {% endif %}
</form>


<section class="container">
        
            <div class="row">
        
                <div class="form_title">模块名称：{{block_instance.title}}</div>
        
                <form class="form_main form-horizontal" action="" method="post"  enctype="multipart/form-data">
                    {%csrf_token%}   
                    {% if block_instance %}
                    <input type="hidden" name="blockid" id="blockid" value="{{block_instance.id}}" />  
                    {% endif %}
                    <div id="add_input">
                    </div>
                    <div class="form-group">
                        <label for="title" class="col-sm-2 control-label">{% trans "title" %}</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="title" name="title" required="required" placeholder="{% trans "title" %}">
                        </div>
                    </div>
        
                    <div class="form-group">
                        <label for="url" class="col-sm-2 control-label">链接</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="url" name="url" title="url" placeholder="url">
                        </div>
                    </div>  
        
                    <div class="form-group">
                        <label for="status" class="col-sm-2 control-label">{% trans "status" %}</label>
                        <div class="col-sm-10">
                                <select class="form-control" id="status" name="status" >
                                        <option value ="0">草稿</option>
                                        <option value ="1">发布</option>
                                </select>
                        </div>
                    </div>
                    <div class="form-group">
                            <label for="mark" class="col-sm-2 control-label">标记</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" id="mark" name="mark" title="{% trans "mark" %}" placeholder="{% trans "mark" %}">
                            </div>
                    </div>
                    <div class="form-group">
                    
                        <div id="wrapper" class="col-sm-2">
                            <input class="hide" id="fileUpload" type="file" name="pic" />
                            <div class="img_wrap" id="image-holder">
                                <img class="thumb-image" src="/static/img/pic1.png" />
                            </div>
                        </div>
                    
                        <div class="col-sm-10">
                            <label id="file" for="fileUpload" class="control-label btn btn-primary" title="上传图片">上传图片
                                    <i class="fa fa-arrow-circle-up" aria-hidden="true"></i>
                            </label>
                            <button type="submit" class="btn btn-primary" title="{% trans "submit" %}">{% trans "submit" %}</button>
                        </div>
        
                    </div>
        
                </form>
                <div class="table_wrap col-sm-12 col-md-12">
                        <table class="table table-striped table-hover table-bordered">
                                <tr>
                                    <th>ID</th>
                                    <th>{% trans "title" %}</th>
                                    <th>{% trans "picture" %}</th>
                                    <th>链接</th>
                                    <th>{% trans "status" %}</th>
                                    <th>{% trans "mark" %}</th>
                                    <th>操作</th>
                                </tr>
                            {% for item in block_instance.adaptorbaseblockitem_set.all %}
                            <tr class="table_con"> 
                                    <td class="b_itemid">{{item.id}}</td>
                                    <td class="b_title"><a target="__blank" href="{{item.url}}">{{item.title}}</a></td>
                                    <td class="b_picture"><a target="_blank" href="{{mediaroot}}{{item.pic}}">点击查看图片</a></td>
                                    <td class="b_url"><a target="_blank" href="{{item.url}}">{{item.url}}</a></td>
                                    {% if item.status == 0 %}
                                    <td class="b_status">草稿</td>
                                    {% else %}
                                    <td class="b_status">发布</td>
                                    {% endif %}
                                    <td class="b_mark">{{item.mark}}</td>
                                <td class="text-center">
                                    <i class="fa fa-pencil-square-o edit" aria-hidden="true" title="编辑"></i>
                                    <i class="fa fa-trash-o" aria-hidden="true" title='删除'></i>
                                </td>
                            </tr>
                            {% endfor %}
                        </table>
                    </div>
            </div>
        </section>

{% endblock %} 
{% block js %}
<script type="text/javascript " src="/static/sitecontent/js/new.js"></script>
 {% endblock %}

sitecontent/templates/sitecontent/test.html
{% extends 'base.html' %}
{% load i18n %}
{% block pagetitle%}{% trans 'Homepage Content Management' %}{% endblock%}
{% block content %}
<!--
<form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%}  
    <input type="hidden" name="blockid" id="blockid" value="4" />  
    <input type="hidden" name="method"   value="put" /> 
    <input type="text" name="title" required="required" placeholder="{% trans 'hot product' %}"  value="" /> 
    <input type="text" name="url"  placeholder="url"  value="" /> 
    <input type="text" name="status"  placeholder="status"  value="" /> 
    <input type="text" name="mark"  placeholder="mark"  value="" /> 
    <input type="file" name="pic" placeholder="pic"  accept="image/*" /> 
    <input type="submit"  value="{% trans 'submit' %}" /> 
</form>
-->
<form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%}   

    <input type="text" name="title" required="required" placeholder="{% trans 'hot product' %}"  value="" /> 
    <input type="text" name="url"  placeholder="url"  value="" /> 
    <input type="text" name="status"  placeholder="status"  value="" /> 
    <input type="text" name="mark"  placeholder="mark"  value="" /> 
    <input type="file" name="pic" placeholder="pic"  accept="image/*" /> 
    <input type="submit"  value="New {% trans 'submit' %}" /> 
</form>


<table class="table">
    {% for blocki in blocks %}
    <tr> 
        <td>{{blocki.id}}</td>
        <td><a target="__blank" href="{% url 'sitecontent:blockitemcontents' %}?new=&blockid={{blocki.id}}">{{blocki.title}}</a></td>
        <td><a target="__blank" href="{{mediaroot}}{{blocki.pic}}">点击查看图片</a></td>
        <td><a target="__blank" href="{{blocki.url}}">{{blocki.url}}</a></td>
        <td>{{blocki.status}}</td>
        <td>{{blocki.mark}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock%}

sitecontent/templates/sitecontent/testitem.html
{% extends 'base.html' %}
{% load i18n %}
{% block pagetitle%}{% trans 'Homepage Content Management' %}{% endblock%}
{% block content %}

{% if block_instance %}
<label type="text"  >模块名称：{{block_instance.title}}</label> 
{% endif %}

<form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%}  
    <input type="hidden" name="itemid" id="itemid" value="3" />  
    <input type="hidden" name="method"   value="put" /> 
    <input type="text" name="title" required="required" placeholder="{% trans 'hot product' %}"  value="" /> 
    <input type="text" name="url"  placeholder="url"  value="" /> 
    <input type="text" name="status"  placeholder="status"  value="" /> 
    <input type="text" name="mark"  placeholder="mark"  value="" /> 
    <input type="file" name="pic" placeholder="pic"  accept="image/*" /> 
    <input type="submit"  value="{% trans 'submit' %}" /> 
</form> 
<!--

<form action="" method="post"  enctype="multipart/form-data">
    {%csrf_token%}   
    {% if block_instance %}
    <input type="hidden" name="blockid" id="blockid" value="{{block_instance.id}}" />  
    {% endif %}
    <input type="text" name="title" required="required" placeholder="{% trans 'hot product' %}"  value="" /> 
    <input type="text" name="url"  placeholder="url"  value="" /> 
    <input type="text" name="status"  placeholder="status"  value="" /> 
    <input type="text" name="mark"  placeholder="mark"  value="" /> 
    <input type="file" name="pic" placeholder="pic"  accept="image/*" /> 
    <input type="submit"  value="New {% trans 'submit' %}" /> 
</form>

-->
<table class="table">
    {% for item in block_instance.adaptorbaseblockitem_set.all %}
    <tr> 
        <td>{{item.id}}</td>
        <td>{{item.title}}</td>
        <td><a target="_blank" href="{{mediaroot}}{{item.pic}}">点击查看图片</a></td>
        <td><a target="_blank" href="{{item.url}}">{{blocki.url}}</a></td>
        {% if item.status == 0 %}
        <td class="b_status">草稿</td>
        {% else %}
        <td class="b_status">发布</td>
        {% endif %}
        <td>{{item.mark}}</td>
    </tr>
    {% endfor %}
</table>

{% endblock%}